NODE_URL = "rest+http://127.0.0.1:1317"
MIN_GAS_FEE = 0.025
CHAIN_ID = "localosmosis"

USDC_DECIMALS = 6
BUSD_DECIMALS = 18
BTC_DECIMALS = 8
ETH_DECIMALS = 18
ATOM_DECIMALS = 6
OSMO_DECIMALS = 6
USDO_DECIMALS = 18

USDC_SCALE = 10**USDC_DECIMALS
BUSD_SCALE = 10**BUSD_DECIMALS
BTC_SCALE = 10**BTC_DECIMALS
ETH_SCALE = 10**ETH_DECIMALS
ATOM_SCALE = 10**ATOM_DECIMALS
OSMO_SCALE = 10**OSMO_DECIMALS
USDO_SCALE = 10**USDO_DECIMALS

PRICE_PRECISION = 10**18
ORACLE_PRICE_PRECISION = 10**8
